---
- hosts: all
  tasks:
  - name: Install all security, critical, and rollup updates without a scheduled task
    win_updates:
      category_names:
        - SecurityUpdates
        - CriticalUpdates
        - UpdateRollups
  - name: copy the bundle
    win_copy:
      src: GoogleChromeEnterpriseBundle64.zip
      dest: C:\\Temp\\
  - name: extract the bundle 
    win_unzip:
      src: c:\\Temp\\GoogleChromeEnterpriseBundle64.zip
      dest: c:\\Temp\\crome 
  - name: install \crome
    win_package:
      path: c:\\Temp\\crome\\Installers\\GoogleChromeStandaloneEnterprise64.msi
      wait: yes
      state: present 
      arguments: /install /passive /norestart
