---
- hosts: all
  tasks:
  - name: Install all security, critical, and rollup updates without a scheduled task
    win_updates:
      category_names:
        - SecurityUpdates
        - CriticalUpdates
        - UpdateRollups
  - name: copy the bundle
    win_copy:
      src: GoogleChromeEnterpriseBundle64.zip
      dest: C:\\Temp\\
  - name: extract the bundle 
    win_unzip:
      src: c:\\Temp\\GoogleChromeEnterpriseBundle64.zip
      dest: c:\\Temp\\crome 
  - name: install 7 zip 
  
    win_package:
      path: https://d3.7-zip.org/a/7z2107-x64.exe
      product_id: 7-Zip
      arguments:
      - /install
      - /passive
      - /norestart