---
- hosts: all
  tasks:
  - name: Install all security, critical, and rollup updates without a scheduled task
    win_updates:
      category_names:
        - SecurityUpdates
        - CriticalUpdates
        - UpdateRollups
  - name: copy the bundle
    win_copy:
      src: GoogleChromeEnterpriseBundle64.zip
      dest: C:\\Temp\\
  - name: extract the bundle 
    win_unzip:
      src: c:\\Temp\\GoogleChromeEnterpriseBundle64.zip
      dest: c:\\Temp\\crome 
  - name: install \crome
    win_package:
    win_package:
      path: https://download.microsoft.com/download/A/F/0/AF0071F3-B198-4A35-AA90-C68D103BDCCF/rdcman.msi
      product_id: '{0240359E-6A4C-4884-9E94-B397A02D893C}'
      state: present